name: Deploy to GH Pages
on:
  push:
    branches: ['master']
  workflow_dispatch:
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 16.14.2
      - name: Install Dependencies
        run: yarn install
      - name: Build Command
        run: yarn build
      - name: Deploy to GH Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
